# 1. DB \uC811\uC18D \uC8FC\uC18C (auth-practice_db \uB85C \uAC00\uB77C!)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-practice_db

# 2. DB \uB9C8\uC2A4\uD130 \uC544\uC774\uB514 (PostgreSQL \uAE30\uBCF8 \uC544\uC774\uB514\uB294 postgres \uC785\uB2C8\uB2E4)
spring.datasource.username=postgres

# 3. DB \uB9C8\uC2A4\uD130 \uBE44\uBC00\uBC88\uD638
spring.datasource.password=1234

# 4. DB \uB4DC\uB77C\uC774\uBC84 (PostgreSQL\uC6A9 \uBC88\uC5ED\uAE30)
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. \uD558\uC774\uBC84\uB124\uC774\uD2B8 \uC124\uC815 (\uC790\uBC14 \uCF54\uB4DC\uB97C \uBCF4\uACE0 DB \uD14C\uC774\uBE14\uC744 \uC790\uB3D9\uC73C\uB85C \uB9CC\uB4E4\uC5B4\uC90C)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ---------------------------------------------------------
# JWT \uC124\uC815
# ---------------------------------------------------------
# JWT \uBE44\uBC00\uD0A4 (\uBCF5\uC7A1\uD55C \uC601\uBB38/\uC22B\uC790 \uC870\uD569, \uCD5C\uC18C 32\uBC14\uC774\uD2B8 \uC774\uC0C1)
jwt.secret=twincleauthpracticejwtsecretkeyfortestpurposeonly12345

# Access Token \uC720\uD6A8\uC2DC\uAC04 (\uBC00\uB9AC\uCD08 \uB2E8\uC704, 1000ms = 1\uCD08) -> 30\uBD84(1,800,000)\uC73C\uB85C \uC124\uC815
jwt.access-token-validity-in-milliseconds=1800000

# Refresh Token \uC720\uD6A8\uC2DC\uAC04 -> 7\uC77C(604,800,000)\uC73C\uB85C \uC124\uC815
jwt.refresh-token-validity-in-milliseconds=604800000