# 1. DB ?? ?? (auth-practice_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-practice_db

# 2. DB ??? ??? (PostgreSQL ?? ???? postgres)
spring.datasource.username=postgres

# 3. DB ??? ????
spring.datasource.password=1234

# 4. DB ???? (PostgreSQL? ???)
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. ?????? ?? (?? ??? ?? DB ???? ???? ????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true